lane :update_tag do
  prefix = ENV['PREFIX']
  version_properties_file = "../popcornguineapigplugin/version.properties"

  UI.message(">>>>prefix #{prefix}")

  version_line = File.readlines(version_properties_file).find { |line| line.start_with?("VERSION=") }
  version_static = version_line.split("=").last.strip

  last_tag = sh("git tag --list '#{prefix}*' --sort=-v:refname | head -n 1").strip

  if last_tag.empty?
    UI.message("No tag found with prefix #{prefix}. Creating the first tag 1.0.0.")
    new_tag = "#{prefix}1.0.0"
    sh("git tag #{new_tag}")
    sh("git push origin #{new_tag}")
    UI.success("First tag created: #{new_tag}")
  else
    stripped_tag = last_tag.gsub(prefix, '')
    version_match = stripped_tag.match(/(\d+)\.(\d+)\.(\d+)/)

    minor = stripped_tag[1].to_i + 1
    newVersion = "\"#{stripped_tag[0]}.#{minor}.0\""

    if (Gem::Version.new("#{stripped_tag}") <= Gem::Version.new("#{version_static}"))
        newVersion = version_static
    end

    new_tag = "#{prefix}#{newVersion}"

    sh("git add #{version_properties_file}")
    sh("git commit -m 'Update version to #{newVersion}'")
    sh("git tag #{new_tag}")
    sh("git push origin #{new_tag}")

    UI.success("New tag created: #{new_tag}")
  end
end
